services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    env_file:
      - ./services/mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgresql:
    image: postgres:15
    container_name: local-postgresql
    env_file:
      - ./services/postgresql/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: local-mongodb
    env_file:
      - ./services/mongodb/.env
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  pg_data:
  mongo_data:
